//
// WARNING: this file was auto-generated by @phensley/cldr-compiler. DO NOT EDIT.
//

import { makeKeyedEnum } from '../../types/enum';

export const [ Unit, UnitValues ] = makeKeyedEnum([
  ['g_force', 'g-force'],
  ['meter_per_second_squared', 'meter-per-second-squared'],
  ['arc_minute', 'arc-minute'],
  ['arc_second', 'arc-second'],
  ['degree', 'degree'],
  ['radian', 'radian'],
  ['revolution', 'revolution'],
  ['acre', 'acre'],
  ['hectare', 'hectare'],
  ['square_centimeter', 'square-centimeter'],
  ['square_foot', 'square-foot'],
  ['square_inch', 'square-inch'],
  ['square_kilometer', 'square-kilometer'],
  ['square_meter', 'square-meter'],
  ['square_mile', 'square-mile'],
  ['square_yard', 'square-yard'],
  ['karat', 'karat'],
  ['milligram_per_deciliter', 'milligram-per-deciliter'],
  ['millimole_per_liter', 'millimole-per-liter'],
  ['part_per_million', 'part-per-million'],
  ['liter_per_100kilometers', 'liter-per-100kilometers'],
  ['liter_per_kilometer', 'liter-per-kilometer'],
  ['mile_per_gallon', 'mile-per-gallon'],
  ['mile_per_gallon_imperial', 'mile-per-gallon-imperial'],
  ['bit', 'bit'],
  ['byte', 'byte'],
  ['gigabit', 'gigabit'],
  ['gigabyte', 'gigabyte'],
  ['kilobit', 'kilobit'],
  ['kilobyte', 'kilobyte'],
  ['megabit', 'megabit'],
  ['megabyte', 'megabyte'],
  ['terabit', 'terabit'],
  ['terabyte', 'terabyte'],
  ['century', 'century'],
  ['day', 'day'],
  ['hour', 'hour'],
  ['microsecond', 'microsecond'],
  ['millisecond', 'millisecond'],
  ['minute', 'minute'],
  ['month', 'month'],
  ['nanosecond', 'nanosecond'],
  ['second', 'second'],
  ['week', 'week'],
  ['year', 'year'],
  ['ampere', 'ampere'],
  ['milliampere', 'milliampere'],
  ['ohm', 'ohm'],
  ['volt', 'volt'],
  ['calorie', 'calorie'],
  ['foodcalorie', 'foodcalorie'],
  ['joule', 'joule'],
  ['kilocalorie', 'kilocalorie'],
  ['kilojoule', 'kilojoule'],
  ['kilowatt_hour', 'kilowatt-hour'],
  ['gigahertz', 'gigahertz'],
  ['hertz', 'hertz'],
  ['kilohertz', 'kilohertz'],
  ['megahertz', 'megahertz'],
  ['astronomical_unit', 'astronomical-unit'],
  ['centimeter', 'centimeter'],
  ['decimeter', 'decimeter'],
  ['fathom', 'fathom'],
  ['foot', 'foot'],
  ['furlong', 'furlong'],
  ['inch', 'inch'],
  ['kilometer', 'kilometer'],
  ['light_year', 'light-year'],
  ['meter', 'meter'],
  ['micrometer', 'micrometer'],
  ['mile', 'mile'],
  ['mile_scandinavian', 'mile-scandinavian'],
  ['millimeter', 'millimeter'],
  ['nanometer', 'nanometer'],
  ['nautical_mile', 'nautical-mile'],
  ['parsec', 'parsec'],
  ['picometer', 'picometer'],
  ['point', 'point'],
  ['yard', 'yard'],
  ['lux', 'lux'],
  ['carat', 'carat'],
  ['gram', 'gram'],
  ['kilogram', 'kilogram'],
  ['metric_ton', 'metric-ton'],
  ['microgram', 'microgram'],
  ['milligram', 'milligram'],
  ['ounce', 'ounce'],
  ['ounce_troy', 'ounce-troy'],
  ['pound', 'pound'],
  ['stone', 'stone'],
  ['ton', 'ton'],
  ['gigawatt', 'gigawatt'],
  ['horsepower', 'horsepower'],
  ['kilowatt', 'kilowatt'],
  ['megawatt', 'megawatt'],
  ['milliwatt', 'milliwatt'],
  ['watt', 'watt'],
  ['hectopascal', 'hectopascal'],
  ['inch_hg', 'inch-hg'],
  ['millibar', 'millibar'],
  ['millimeter_of_mercury', 'millimeter-of-mercury'],
  ['pound_per_square_inch', 'pound-per-square-inch'],
  ['kilometer_per_hour', 'kilometer-per-hour'],
  ['knot', 'knot'],
  ['meter_per_second', 'meter-per-second'],
  ['mile_per_hour', 'mile-per-hour'],
  ['celsius', 'celsius'],
  ['fahrenheit', 'fahrenheit'],
  ['generic', 'generic'],
  ['kelvin', 'kelvin'],
  ['acre_foot', 'acre-foot'],
  ['bushel', 'bushel'],
  ['centiliter', 'centiliter'],
  ['cubic_centimeter', 'cubic-centimeter'],
  ['cubic_foot', 'cubic-foot'],
  ['cubic_inch', 'cubic-inch'],
  ['cubic_kilometer', 'cubic-kilometer'],
  ['cubic_meter', 'cubic-meter'],
  ['cubic_mile', 'cubic-mile'],
  ['cubic_yard', 'cubic-yard'],
  ['cup', 'cup'],
  ['cup_metric', 'cup-metric'],
  ['deciliter', 'deciliter'],
  ['fluid_ounce', 'fluid-ounce'],
  ['gallon', 'gallon'],
  ['gallon_imperial', 'gallon-imperial'],
  ['hectoliter', 'hectoliter'],
  ['liter', 'liter'],
  ['megaliter', 'megaliter'],
  ['milliliter', 'milliliter'],
  ['pint', 'pint'],
  ['pint_metric', 'pint-metric'],
  ['quart', 'quart'],
  ['tablespoon', 'tablespoon'],
  ['teaspoon', 'teaspoon'],
]);

export type UnitType =   'g-force' |  'meter-per-second-squared' |  'arc-minute'
 |  'arc-second' |  'degree' |  'radian' |  'revolution' |  'acre'
 |  'hectare' |  'square-centimeter' |  'square-foot'
 |  'square-inch' |  'square-kilometer' |  'square-meter'
 |  'square-mile' |  'square-yard' |  'karat'
 |  'milligram-per-deciliter' |  'millimole-per-liter'
 |  'part-per-million' |  'liter-per-100kilometers'
 |  'liter-per-kilometer' |  'mile-per-gallon'
 |  'mile-per-gallon-imperial' |  'bit' |  'byte' |  'gigabit'
 |  'gigabyte' |  'kilobit' |  'kilobyte' |  'megabit' |  'megabyte'
 |  'terabit' |  'terabyte' |  'century' |  'day' |  'hour'
 |  'microsecond' |  'millisecond' |  'minute' |  'month'
 |  'nanosecond' |  'second' |  'week' |  'year' |  'ampere'
 |  'milliampere' |  'ohm' |  'volt' |  'calorie' |  'foodcalorie'
 |  'joule' |  'kilocalorie' |  'kilojoule' |  'kilowatt-hour'
 |  'gigahertz' |  'hertz' |  'kilohertz' |  'megahertz'
 |  'astronomical-unit' |  'centimeter' |  'decimeter' |  'fathom'
 |  'foot' |  'furlong' |  'inch' |  'kilometer' |  'light-year'
 |  'meter' |  'micrometer' |  'mile' |  'mile-scandinavian'
 |  'millimeter' |  'nanometer' |  'nautical-mile' |  'parsec'
 |  'picometer' |  'point' |  'yard' |  'lux' |  'carat' |  'gram'
 |  'kilogram' |  'metric-ton' |  'microgram' |  'milligram'
 |  'ounce' |  'ounce-troy' |  'pound' |  'stone' |  'ton'
 |  'gigawatt' |  'horsepower' |  'kilowatt' |  'megawatt'
 |  'milliwatt' |  'watt' |  'hectopascal' |  'inch-hg'
 |  'millibar' |  'millimeter-of-mercury'
 |  'pound-per-square-inch' |  'kilometer-per-hour' |  'knot'
 |  'meter-per-second' |  'mile-per-hour' |  'celsius'
 |  'fahrenheit' |  'generic' |  'kelvin' |  'acre-foot' |  'bushel'
 |  'centiliter' |  'cubic-centimeter' |  'cubic-foot'
 |  'cubic-inch' |  'cubic-kilometer' |  'cubic-meter'
 |  'cubic-mile' |  'cubic-yard' |  'cup' |  'cup-metric'
 |  'deciliter' |  'fluid-ounce' |  'gallon' |  'gallon-imperial'
 |  'hectoliter' |  'liter' |  'megaliter' |  'milliliter' |  'pint'
 |  'pint-metric' |  'quart' |  'tablespoon' |  'teaspoon';