#!/bin/bash

MESSAGE="Outdated pre-release version"
VERSIONS=$*

PACKAGES="
@phensley/cldr
@phensley/cldr-compiler
@phensley/cldr-core
@phensley/cldr-ext-rbnf
@phensley/cldr-types
@phensley/cldr-utils
@phensley/decimal
@phensley/language-tag
@phensley/locale
@phensley/locale-matcher
@phensley/messageformat
@phensley/plurals
@phensley/timezone
"
for version in $VERSIONS ; do
    for pkg in $PACKAGES ; do
        echo $pkg $version
        npm deprecate $pkg@$version "$MESSAGE"
    done
done


