#!/bin/bash

REG=$(npm config get registry)
if [[ $REG != *"registry.npmjs.org"* ]] ; then
    echo "Please configure the official NPM registry. Found $REG"
    exit 1
fi

# ensure packages are installed
yarn

# wipe everything out
yarn clean:full
rm -f yarn.lock

# install again
yarn
yarn clean

# build and lint
yarn lint

# publish packages
lerna publish --exact --force-publish=* $*

