#!/bin/bash

REG=$(npm config get registry)
if [[ $REG != *"registry.npmjs.org"* ]] ; then
    echo "Please configure the official NPM registry. Found $REG"
    exit 1
fi

yarn
lerna run clean
lerna run lint
lerna publish --exact --force-publish=* --npm-client=npm $*

