//
// WARNING: this file was auto-generated by @phensley/cldr-compiler. DO NOT EDIT.
//

/* tslint:disable:max-line-length */
export const algorithmicNumbering: { [x: string]: [string, string] } = {
  armn: ['root', 'armenian-upper'],
  armnlow: ['root', 'armenian-lower'],
  cyrl: ['root', 'cyrillic-lower'],
  ethi: ['root', 'ethiopic'],
  geor: ['root', 'georgian'],
  grek: ['root', 'greek-upper'],
  greklow: ['root', 'greek-lower'],
  hanidays: ['zh-Hans', 'spellout-numbering-days'],
  hans: ['zh-Hans', 'spellout-cardinal'],
  hansfin: ['zh-Hans', 'spellout-cardinal-financial'],
  hant: ['zh-Hant', 'spellout-cardinal'],
  hantfin: ['zh-Hant', 'spellout-cardinal-financial'],
  hebr: ['root', 'hebrew'],
  jpan: ['ja-Jpan', 'spellout-cardinal'],
  jpanfin: ['ja-Jpan', 'spellout-cardinal-financial'],
  jpanyear: ['ja-Jpan', 'spellout-numbering-year-latn'],
  roman: ['root', 'roman-upper'],
  romanlow: ['root', 'roman-lower'],
  taml: ['root', 'tamil'],
};
