//
// WARNING: this file was auto-generated by @phensley/cldr-compiler. DO NOT EDIT.
//

/* tslint:disable:max-line-length */

export type UnitType =   'g-force' |  'meter-per-second-squared' |  'arc-minute'
 |  'arc-second' |  'degree' |  'radian' |  'revolution' |  'acre'
 |  'dunam' |  'hectare' |  'square-centimeter' |  'square-foot'
 |  'square-inch' |  'square-kilometer' |  'square-meter'
 |  'square-mile' |  'square-yard' |  'karat'
 |  'milligram-per-deciliter' |  'millimole-per-liter' |  'mole'
 |  'part-per-million' |  'percent' |  'permille' |  'permyriad'
 |  'liter-per-100kilometers' |  'liter-per-kilometer'
 |  'mile-per-gallon' |  'mile-per-gallon-imperial' |  'bit'
 |  'byte' |  'gigabit' |  'gigabyte' |  'kilobit' |  'kilobyte'
 |  'megabit' |  'megabyte' |  'petabyte' |  'terabit' |  'terabyte'
 |  'century' |  'day' |  'decade' |  'hour' |  'microsecond'
 |  'millisecond' |  'minute' |  'month' |  'nanosecond' |  'second'
 |  'week' |  'year' |  'ampere' |  'milliampere' |  'ohm' |  'volt'
 |  'british-thermal-unit' |  'calorie' |  'electronvolt'
 |  'foodcalorie' |  'joule' |  'kilocalorie' |  'kilojoule'
 |  'kilowatt-hour' |  'therm-us' |  'newton' |  'pound-force'
 |  'gigahertz' |  'hertz' |  'kilohertz' |  'megahertz'
 |  'dot-per-centimeter' |  'dot-per-inch' |  'em' |  'megapixel'
 |  'pixel' |  'pixel-per-centimeter' |  'pixel-per-inch'
 |  'astronomical-unit' |  'centimeter' |  'decimeter' |  'fathom'
 |  'foot' |  'furlong' |  'inch' |  'kilometer' |  'light-year'
 |  'meter' |  'micrometer' |  'mile' |  'mile-scandinavian'
 |  'millimeter' |  'nanometer' |  'nautical-mile' |  'parsec'
 |  'picometer' |  'point' |  'solar-radius' |  'yard' |  'lux'
 |  'solar-luminosity' |  'carat' |  'dalton' |  'earth-mass'
 |  'gram' |  'kilogram' |  'metric-ton' |  'microgram'
 |  'milligram' |  'ounce' |  'ounce-troy' |  'pound'
 |  'solar-mass' |  'stone' |  'ton' |  'gigawatt' |  'horsepower'
 |  'kilowatt' |  'megawatt' |  'milliwatt' |  'watt'
 |  'atmosphere' |  'bar' |  'hectopascal' |  'inch-hg'
 |  'kilopascal' |  'megapascal' |  'millibar'
 |  'millimeter-of-mercury' |  'pascal'
 |  'pound-per-square-inch' |  'kilometer-per-hour' |  'knot'
 |  'meter-per-second' |  'mile-per-hour' |  'celsius'
 |  'fahrenheit' |  'generic' |  'kelvin' |  'newton-meter'
 |  'pound-foot' |  'acre-foot' |  'barrel' |  'bushel'
 |  'centiliter' |  'cubic-centimeter' |  'cubic-foot'
 |  'cubic-inch' |  'cubic-kilometer' |  'cubic-meter'
 |  'cubic-mile' |  'cubic-yard' |  'cup' |  'cup-metric'
 |  'deciliter' |  'fluid-ounce' |  'fluid-ounce-imperial'
 |  'gallon' |  'gallon-imperial' |  'hectoliter' |  'liter'
 |  'megaliter' |  'milliliter' |  'pint' |  'pint-metric'
 |  'quart' |  'tablespoon' |  'teaspoon';

export type UnitCategory =   'acceleration' |  'angle' |  'area' |  'concentr'
 |  'consumption' |  'digital' |  'duration' |  'electric'
 |  'energy' |  'force' |  'frequency' |  'graphics' |  'length'
 |  'light' |  'mass' |  'power' |  'pressure' |  'speed'
 |  'temperature' |  'torque' |  'volume';

export const unitCategories: UnitCategory[] = ['acceleration', 'angle', 'area', 'concentr', 'consumption', 'digital', 'duration', 'electric', 'energy', 'force', 'frequency', 'graphics', 'length', 'light', 'mass', 'power', 'pressure', 'speed', 'temperature', 'torque', 'volume'];

// Minimal perfect hash mapping units to the index of their category
export const unitCategoryMapG: number[] = [-140, 0, 0, -146, 0, 1, -119, 0, 0, 0, 0, -50, -49, -35, -161, -159, 0, 0, -149, 2, 3, 0, 0, -132, -128, 1, 0, -111, -109, 0, 1, -102, 0, 0, 0, 0, -54, 0, 2, -39, 2, -29, -26, -166, 6, 1, 1, 0, 1, 1, 0, 1, -141, 5, 0, -137, -136, 1, 7, 0, 1, -127, -126, 1, 0, 0, 3, -113, 1, 3, 5, 0, 7, 0, 0, 0, 0, -89, -88, 0, 3, -82, 2, 0, 0, -75, -168, -71, 0, 0, -61, 6, 5, 0, -43, 0, 0, 12, 0, 13, 0, -24, 0, 0, -21, 0, 0, 1, 0, 0, -32, 0, 3, 0, 0, -41, 1, -67, -68, 0, -73, 2, 0, -77, -86, -92, 5, 0, -99, 4, -107, 0, 0, -116, -117, -129, -138, 0, 0, -143, 8, 1, 1, -80, -83, 0, 0, 2, 1, 0, -114, -133, 0, 10, 0, -150, 0, 0, 0, 0, 0, 0, -152, -76, 0, 0, 1, 0, -103, -108, -142, -94, 0];
export const unitCategoryMapV: (number | undefined)[] = [, 20, 18, 20, 12, 20, 2, 8, 9, 17, , , 12, 20, 14, 0, 12, 18, , , 12, 15, 1, 12, 2, 14, 8, 7, 3, 20, 5, 8, 12, 2, 8, 14, 5, 15, 5, 12, 3, 2, 20, 16, 14, 14, 19, 12, 0, 10, 20, 5, 20, 11, 20, 4, 16, 11, 20, 1, 20, 2, 15, 2, 12, 20, 2, 12, 11, 9, 17, 5, 14, 7, 5, 13, 3, 16, 12, 16, 2, 3, 12, 8, 14, 5, 12, 12, 14, 14, 10, 3, 8, 8, 6, 20, 5, 6, 1, 5, 20, 12, 20, 7, 11, 14, 10, 11, 20, 8, 7, 20, 14, 14, 16, 16, 14, 20, 20, 3, 14, 6, 6, 20, 20, 5, 19, 6, 16, 12, 16, 6, 20, 4, 11, 17, 20, 18, 2, 2, 15, 3, 6, 5, 20, 20, 1, 12, 15, 15, 18, 17, 13, 12, 4, 20, 6, 3, 12, 11, 12, 4, 6, 12, 8, 1, 6, 20, 6, 6, 16, 10, 16];
export const unitCategoryMapS: number = 173;
