//
// WARNING: this file was auto-generated by @phensley/cldr-compiler. DO NOT EDIT.
//

/* tslint:disable:max-line-length */

/** @public */
export type UnitType =   'g-force' |  'meter-per-second-squared' |  'arc-minute'
 |  'arc-second' |  'degree' |  'radian' |  'revolution' |  'acre'
 |  'dunam' |  'hectare' |  'square-centimeter' |  'square-foot'
 |  'square-inch' |  'square-kilometer' |  'square-meter'
 |  'square-mile' |  'square-yard' |  'karat'
 |  'milligram-per-deciliter' |  'millimole-per-liter' |  'mole'
 |  'part-per-million' |  'percent' |  'permille' |  'permyriad'
 |  'liter-per-100kilometers' |  'liter-per-kilometer'
 |  'mile-per-gallon' |  'mile-per-gallon-imperial' |  'bit'
 |  'byte' |  'gigabit' |  'gigabyte' |  'kilobit' |  'kilobyte'
 |  'megabit' |  'megabyte' |  'petabyte' |  'terabit' |  'terabyte'
 |  'century' |  'day' |  'decade' |  'hour' |  'microsecond'
 |  'millisecond' |  'minute' |  'month' |  'nanosecond' |  'second'
 |  'week' |  'year' |  'ampere' |  'milliampere' |  'ohm' |  'volt'
 |  'british-thermal-unit' |  'calorie' |  'electronvolt'
 |  'foodcalorie' |  'joule' |  'kilocalorie' |  'kilojoule'
 |  'kilowatt-hour' |  'therm-us' |  'newton' |  'pound-force'
 |  'gigahertz' |  'hertz' |  'kilohertz' |  'megahertz'
 |  'dot-per-centimeter' |  'dot-per-inch' |  'em' |  'megapixel'
 |  'pixel' |  'pixel-per-centimeter' |  'pixel-per-inch'
 |  'astronomical-unit' |  'centimeter' |  'decimeter' |  'fathom'
 |  'foot' |  'furlong' |  'inch' |  'kilometer' |  'light-year'
 |  'meter' |  'micrometer' |  'mile' |  'mile-scandinavian'
 |  'millimeter' |  'nanometer' |  'nautical-mile' |  'parsec'
 |  'picometer' |  'point' |  'solar-radius' |  'yard' |  'lux'
 |  'solar-luminosity' |  'carat' |  'dalton' |  'earth-mass'
 |  'gram' |  'kilogram' |  'metric-ton' |  'microgram'
 |  'milligram' |  'ounce' |  'ounce-troy' |  'pound'
 |  'solar-mass' |  'stone' |  'ton' |  'gigawatt' |  'horsepower'
 |  'kilowatt' |  'megawatt' |  'milliwatt' |  'watt'
 |  'atmosphere' |  'bar' |  'hectopascal' |  'inch-hg'
 |  'kilopascal' |  'megapascal' |  'millibar'
 |  'millimeter-of-mercury' |  'pascal'
 |  'pound-per-square-inch' |  'kilometer-per-hour' |  'knot'
 |  'meter-per-second' |  'mile-per-hour' |  'celsius'
 |  'fahrenheit' |  'temperature' |  'kelvin' |  'newton-meter'
 |  'pound-foot' |  'acre-foot' |  'barrel' |  'bushel'
 |  'centiliter' |  'cubic-centimeter' |  'cubic-foot'
 |  'cubic-inch' |  'cubic-kilometer' |  'cubic-meter'
 |  'cubic-mile' |  'cubic-yard' |  'cup' |  'cup-metric'
 |  'deciliter' |  'fluid-ounce' |  'fluid-ounce-imperial'
 |  'gallon' |  'gallon-imperial' |  'hectoliter' |  'liter'
 |  'megaliter' |  'milliliter' |  'pint' |  'pint-metric'
 |  'quart' |  'tablespoon' |  'teaspoon';

/** @public */
export type UnitCategory =   'acceleration' |  'angle' |  'area' |  'concentr'
 |  'consumption' |  'digital' |  'duration' |  'electric'
 |  'energy' |  'force' |  'frequency' |  'graphics' |  'length'
 |  'light' |  'mass' |  'power' |  'pressure' |  'speed'
 |  'temperature' |  'torque' |  'volume';
