#!/usr/bin/env python

import os
from collections import defaultdict

CWD = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(CWD, '../packages/cldr-compiler/.cldr/41.0.0/main')

MAIN = [
  'ca-buddhist',
  'ca-gregorian', 
  'ca-japanese', 
  'ca-persian', 
  'characters',
  'contextTransforms',
  'currencies', 
  'dateFields', 
  'languages', 
  'layout',
  'listPatterns', 
  'numbers', 
  'scripts', 
  'territories', 
  'timeZoneNames',
  'units'
]

def sumall(id):
    size = 0
    for m in MAIN:
        path = os.path.join(ROOT, id, '%s.json' % m)
        if os.path.exists(path):
            size += os.stat(path).st_size
    return size

locales = os.listdir(ROOT)

langs = defaultdict(list)
for id in locales:
    lang = id.split('-')[0]
    langs[lang].append(id)

sums = []
for lang in sorted(langs.keys()):
    size = 0
    for id in sorted(langs[lang]):
        size += sumall(id)
    sums.append((size, lang))

for size, lang in sorted(sums, reverse=1):
    sz = '{:,.0f} KB'.format(size / 1024).rjust(12)
    print('%s  %s' % (sz, lang))
#    print('%12d  %5d KB' % (size, size/1024), lang)

