#!/bin/bash

# Notes on package upgrade exclusions:

# chalk: 5.x is an ESM module now, incompatible with the CommonJS side of our
# project
#
# minimatch 8.x generates a typescript error when compiling ES5
# 
# eslint 9.x flat config support requires many changes
#
# yargs 18 breaking changes, missing @types/yargs update

PIN="
@types/node-fetch
chalk
minimatch
node-fetch
yargs
"

join() {
  local IFS="$1"
  shift
  echo "$*"
}

PINNED=`join , $PIN`

ncu -u -x $PINNED
pnpm --stream -r exec -- ncu -u -x $PINNED

