#!/bin/bash

# Notes on package upgrade exclusions:

# chalk: 5.x is an ESM module now, incompatible with the CommonJS side of our
# project
#
# minimatch 8.x generates a typescript error when compiling ES5

PIN="
@types/node-fetch
node-fetch
chalk
minimatch
"

join() {
  local IFS="$1"
  shift
  echo "$*"
}

PINNED=`join , $PIN`

ncu -u -x $PINNED
pnpm --stream -r exec -- ncu -u -x $PINNED

