import { languageBundle } from './bundle';
import { Bundle } from '../../src/resource';

export const AZ: Bundle = languageBundle('az');
export const AR: Bundle = languageBundle('ar');
export const AR_IL: Bundle = languageBundle('ar-IL');
export const BE: Bundle = languageBundle('be');
export const DE: Bundle = languageBundle('de');
export const EN: Bundle = languageBundle('en');
export const EN_GB: Bundle = languageBundle('en-GB');
export const ES: Bundle = languageBundle('es');
export const ES_419: Bundle = languageBundle('es-419');
export const FR: Bundle = languageBundle('fr');
export const KM: Bundle = languageBundle('km');
export const LT: Bundle = languageBundle('lt');
export const PL: Bundle = languageBundle('pl');
export const SR: Bundle = languageBundle('sr');
export const TH: Bundle = languageBundle('th');
export const ZH: Bundle = languageBundle('zh');
