//
// WARNING: this file was auto-generated by @phensley/cldr-compiler. DO NOT EDIT.
//

export type LanguageIdType = (
  'aa'| 'ab'| 'ace'| 'ach'| 'ada'| 'ady'| 'ae'| 'aeb'| 'af'| 'afh'| 'agq'
| 'ain'| 'ak'| 'akk'| 'akz'| 'ale'| 'aln'| 'alt'| 'am'| 'an'| 'ang'| 'anp'
| 'ar'| 'arc'| 'arn'| 'aro'| 'arp'| 'arq'| 'ars'| 'arw'| 'ary'| 'arz'| 'as'
| 'asa'| 'ase'| 'ast'| 'av'| 'avk'| 'awa'| 'ay'| 'az'| 'ba'| 'bal'| 'ban'
| 'bar'| 'bas'| 'bax'| 'bbc'| 'bbj'| 'be'| 'bej'| 'bem'| 'bew'| 'bez'| 'bfd'
| 'bfq'| 'bg'| 'bgn'| 'bho'| 'bi'| 'bik'| 'bin'| 'bjn'| 'bkm'| 'bla'| 'bm'
| 'bn'| 'bo'| 'bpy'| 'bqi'| 'br'| 'bra'| 'brh'| 'brx'| 'bs'| 'bss'| 'bua'
| 'bug'| 'bum'| 'byn'| 'byv'| 'ca'| 'cad'| 'car'| 'cay'| 'cch'| 'ccp'| 'ce'
| 'ceb'| 'cgg'| 'ch'| 'chb'| 'chg'| 'chk'| 'chm'| 'chn'| 'cho'| 'chp'| 'chr'
| 'chy'| 'ckb'| 'co'| 'cop'| 'cps'| 'cr'| 'crh'| 'crs'| 'cs'| 'csb'| 'cu'
| 'cv'| 'cy'| 'da'| 'dak'| 'dar'| 'dav'| 'de'| 'del'| 'den'| 'dgr'| 'din'
| 'dje'| 'doi'| 'dsb'| 'dtp'| 'dua'| 'dum'| 'dv'| 'dyo'| 'dyu'| 'dz'| 'dzg'
| 'ebu'| 'ee'| 'efi'| 'egl'| 'egy'| 'eka'| 'el'| 'elx'| 'en'| 'enm'| 'eo'
| 'es'| 'esu'| 'et'| 'eu'| 'ewo'| 'ext'| 'fa'| 'fan'| 'fat'| 'ff'| 'fi'| 'fil'
| 'fit'| 'fj'| 'fo'| 'fon'| 'fr'| 'frc'| 'frm'| 'fro'| 'frp'| 'frr'| 'frs'
| 'fur'| 'fy'| 'ga'| 'gaa'| 'gag'| 'gan'| 'gay'| 'gba'| 'gbz'| 'gd'| 'gez'
| 'gil'| 'gl'| 'glk'| 'gmh'| 'gn'| 'goh'| 'gom'| 'gon'| 'gor'| 'got'| 'grb'
| 'grc'| 'gsw'| 'gu'| 'guc'| 'gur'| 'guz'| 'gv'| 'gwi'| 'ha'| 'hai'| 'hak'
| 'haw'| 'he'| 'hi'| 'hif'| 'hil'| 'hit'| 'hmn'| 'ho'| 'hr'| 'hsb'| 'hsn'
| 'ht'| 'hu'| 'hup'| 'hy'| 'hz'| 'ia'| 'iba'| 'ibb'| 'id'| 'ie'| 'ig'| 'ii'
| 'ik'| 'ilo'| 'inh'| 'io'| 'is'| 'it'| 'iu'| 'izh'| 'ja'| 'jam'| 'jbo'| 'jgo'
| 'jmc'| 'jpr'| 'jrb'| 'jut'| 'jv'| 'ka'| 'kaa'| 'kab'| 'kac'| 'kaj'| 'kam'
| 'kaw'| 'kbd'| 'kbl'| 'kcg'| 'kde'| 'kea'| 'ken'| 'kfo'| 'kg'| 'kgp'| 'kha'
| 'kho'| 'khq'| 'khw'| 'ki'| 'kiu'| 'kj'| 'kk'| 'kkj'| 'kl'| 'kln'| 'km'
| 'kmb'| 'kn'| 'ko'| 'koi'| 'kok'| 'kos'| 'kpe'| 'kr'| 'krc'| 'kri'| 'krj'
| 'krl'| 'kru'| 'ks'| 'ksb'| 'ksf'| 'ksh'| 'ku'| 'kum'| 'kut'| 'kv'| 'kw'
| 'ky'| 'la'| 'lad'| 'lag'| 'lah'| 'lam'| 'lb'| 'lez'| 'lfn'| 'lg'| 'li'
| 'lij'| 'liv'| 'lkt'| 'lmo'| 'ln'| 'lo'| 'lol'| 'lou'| 'loz'| 'lrc'| 'lt'
| 'ltg'| 'lu'| 'lua'| 'lui'| 'lun'| 'luo'| 'lus'| 'luy'| 'lv'| 'lzh'| 'lzz'
| 'mad'| 'maf'| 'mag'| 'mai'| 'mak'| 'man'| 'mas'| 'mde'| 'mdf'| 'mdr'| 'men'
| 'mer'| 'mfe'| 'mg'| 'mga'| 'mgh'| 'mgo'| 'mh'| 'mi'| 'mic'| 'min'| 'mk'
| 'ml'| 'mn'| 'mnc'| 'mni'| 'moh'| 'mos'| 'mr'| 'mrj'| 'ms'| 'mt'| 'mua'
| 'mul'| 'mus'| 'mwl'| 'mwr'| 'mwv'| 'my'| 'mye'| 'myv'| 'mzn'| 'na'| 'nan'
| 'nap'| 'naq'| 'nb'| 'nd'| 'nds'| 'ne'| 'new'| 'ng'| 'nia'| 'niu'| 'njo'
| 'nl'| 'nmg'| 'nn'| 'nnh'| 'no'| 'nog'| 'non'| 'nov'| 'nqo'| 'nr'| 'nso'
| 'nus'| 'nv'| 'nwc'| 'ny'| 'nym'| 'nyn'| 'nyo'| 'nzi'| 'oc'| 'oj'| 'om'| 'or'
| 'os'| 'osa'| 'ota'| 'pa'| 'pag'| 'pal'| 'pam'| 'pap'| 'pau'| 'pcd'| 'pcm'
| 'pdc'| 'pdt'| 'peo'| 'pfl'| 'phn'| 'pi'| 'pl'| 'pms'| 'pnt'| 'pon'| 'prg'
| 'pro'| 'ps'| 'pt'| 'qu'| 'quc'| 'qug'| 'raj'| 'rap'| 'rar'| 'rgn'| 'rif'
| 'rm'| 'rn'| 'ro'| 'rof'| 'rom'| 'root'| 'rtm'| 'ru'| 'rue'| 'rug'| 'rup'
| 'rw'| 'rwk'| 'sa'| 'sad'| 'sah'| 'sam'| 'saq'| 'sas'| 'sat'| 'saz'| 'sba'
| 'sbp'| 'sc'| 'scn'| 'sco'| 'sd'| 'sdc'| 'sdh'| 'se'| 'see'| 'seh'| 'sei'
| 'sel'| 'ses'| 'sg'| 'sga'| 'sgs'| 'sh'| 'shi'| 'shn'| 'shu'| 'si'| 'sid'
| 'sk'| 'sl'| 'sli'| 'sly'| 'sm'| 'sma'| 'smj'| 'smn'| 'sms'| 'sn'| 'snk'
| 'so'| 'sog'| 'sq'| 'sr'| 'srn'| 'srr'| 'ss'| 'ssy'| 'st'| 'stq'| 'su'| 'suk'
| 'sus'| 'sux'| 'sv'| 'sw'| 'swb'| 'syc'| 'syr'| 'szl'| 'ta'| 'tcy'| 'te'
| 'tem'| 'teo'| 'ter'| 'tet'| 'tg'| 'th'| 'ti'| 'tig'| 'tiv'| 'tk'| 'tkl'
| 'tkr'| 'tl'| 'tlh'| 'tli'| 'tly'| 'tmh'| 'tn'| 'to'| 'tog'| 'tpi'| 'tr'
| 'tru'| 'trv'| 'ts'| 'tsd'| 'tsi'| 'tt'| 'ttt'| 'tum'| 'tvl'| 'tw'| 'twq'
| 'ty'| 'tyv'| 'tzm'| 'udm'| 'ug'| 'uga'| 'uk'| 'umb'| 'und'| 'ur'| 'uz'
| 'vai'| 've'| 'vec'| 'vep'| 'vi'| 'vls'| 'vmf'| 'vo'| 'vot'| 'vro'| 'vun'
| 'wa'| 'wae'| 'wal'| 'war'| 'was'| 'wbp'| 'wo'| 'wuu'| 'xal'| 'xh'| 'xmf'
| 'xog'| 'yao'| 'yap'| 'yav'| 'ybb'| 'yi'| 'yo'| 'yrl'| 'yue'| 'za'| 'zap'
| 'zbl'| 'zea'| 'zen'| 'zgh'| 'zh'| 'zu'| 'zun'| 'zxx'| 'zza');

export const LanguageIdValues: LanguageIdType[] = [
  'aa', 'ab', 'ace', 'ach', 'ada', 'ady', 'ae', 'aeb', 'af', 'afh', 'agq'
, 'ain', 'ak', 'akk', 'akz', 'ale', 'aln', 'alt', 'am', 'an', 'ang', 'anp'
, 'ar', 'arc', 'arn', 'aro', 'arp', 'arq', 'ars', 'arw', 'ary', 'arz', 'as'
, 'asa', 'ase', 'ast', 'av', 'avk', 'awa', 'ay', 'az', 'ba', 'bal', 'ban'
, 'bar', 'bas', 'bax', 'bbc', 'bbj', 'be', 'bej', 'bem', 'bew', 'bez', 'bfd'
, 'bfq', 'bg', 'bgn', 'bho', 'bi', 'bik', 'bin', 'bjn', 'bkm', 'bla', 'bm'
, 'bn', 'bo', 'bpy', 'bqi', 'br', 'bra', 'brh', 'brx', 'bs', 'bss', 'bua'
, 'bug', 'bum', 'byn', 'byv', 'ca', 'cad', 'car', 'cay', 'cch', 'ccp', 'ce'
, 'ceb', 'cgg', 'ch', 'chb', 'chg', 'chk', 'chm', 'chn', 'cho', 'chp', 'chr'
, 'chy', 'ckb', 'co', 'cop', 'cps', 'cr', 'crh', 'crs', 'cs', 'csb', 'cu'
, 'cv', 'cy', 'da', 'dak', 'dar', 'dav', 'de', 'del', 'den', 'dgr', 'din'
, 'dje', 'doi', 'dsb', 'dtp', 'dua', 'dum', 'dv', 'dyo', 'dyu', 'dz', 'dzg'
, 'ebu', 'ee', 'efi', 'egl', 'egy', 'eka', 'el', 'elx', 'en', 'enm', 'eo'
, 'es', 'esu', 'et', 'eu', 'ewo', 'ext', 'fa', 'fan', 'fat', 'ff', 'fi', 'fil'
, 'fit', 'fj', 'fo', 'fon', 'fr', 'frc', 'frm', 'fro', 'frp', 'frr', 'frs'
, 'fur', 'fy', 'ga', 'gaa', 'gag', 'gan', 'gay', 'gba', 'gbz', 'gd', 'gez'
, 'gil', 'gl', 'glk', 'gmh', 'gn', 'goh', 'gom', 'gon', 'gor', 'got', 'grb'
, 'grc', 'gsw', 'gu', 'guc', 'gur', 'guz', 'gv', 'gwi', 'ha', 'hai', 'hak'
, 'haw', 'he', 'hi', 'hif', 'hil', 'hit', 'hmn', 'ho', 'hr', 'hsb', 'hsn'
, 'ht', 'hu', 'hup', 'hy', 'hz', 'ia', 'iba', 'ibb', 'id', 'ie', 'ig', 'ii'
, 'ik', 'ilo', 'inh', 'io', 'is', 'it', 'iu', 'izh', 'ja', 'jam', 'jbo', 'jgo'
, 'jmc', 'jpr', 'jrb', 'jut', 'jv', 'ka', 'kaa', 'kab', 'kac', 'kaj', 'kam'
, 'kaw', 'kbd', 'kbl', 'kcg', 'kde', 'kea', 'ken', 'kfo', 'kg', 'kgp', 'kha'
, 'kho', 'khq', 'khw', 'ki', 'kiu', 'kj', 'kk', 'kkj', 'kl', 'kln', 'km'
, 'kmb', 'kn', 'ko', 'koi', 'kok', 'kos', 'kpe', 'kr', 'krc', 'kri', 'krj'
, 'krl', 'kru', 'ks', 'ksb', 'ksf', 'ksh', 'ku', 'kum', 'kut', 'kv', 'kw'
, 'ky', 'la', 'lad', 'lag', 'lah', 'lam', 'lb', 'lez', 'lfn', 'lg', 'li'
, 'lij', 'liv', 'lkt', 'lmo', 'ln', 'lo', 'lol', 'lou', 'loz', 'lrc', 'lt'
, 'ltg', 'lu', 'lua', 'lui', 'lun', 'luo', 'lus', 'luy', 'lv', 'lzh', 'lzz'
, 'mad', 'maf', 'mag', 'mai', 'mak', 'man', 'mas', 'mde', 'mdf', 'mdr', 'men'
, 'mer', 'mfe', 'mg', 'mga', 'mgh', 'mgo', 'mh', 'mi', 'mic', 'min', 'mk'
, 'ml', 'mn', 'mnc', 'mni', 'moh', 'mos', 'mr', 'mrj', 'ms', 'mt', 'mua'
, 'mul', 'mus', 'mwl', 'mwr', 'mwv', 'my', 'mye', 'myv', 'mzn', 'na', 'nan'
, 'nap', 'naq', 'nb', 'nd', 'nds', 'ne', 'new', 'ng', 'nia', 'niu', 'njo'
, 'nl', 'nmg', 'nn', 'nnh', 'no', 'nog', 'non', 'nov', 'nqo', 'nr', 'nso'
, 'nus', 'nv', 'nwc', 'ny', 'nym', 'nyn', 'nyo', 'nzi', 'oc', 'oj', 'om', 'or'
, 'os', 'osa', 'ota', 'pa', 'pag', 'pal', 'pam', 'pap', 'pau', 'pcd', 'pcm'
, 'pdc', 'pdt', 'peo', 'pfl', 'phn', 'pi', 'pl', 'pms', 'pnt', 'pon', 'prg'
, 'pro', 'ps', 'pt', 'qu', 'quc', 'qug', 'raj', 'rap', 'rar', 'rgn', 'rif'
, 'rm', 'rn', 'ro', 'rof', 'rom', 'root', 'rtm', 'ru', 'rue', 'rug', 'rup'
, 'rw', 'rwk', 'sa', 'sad', 'sah', 'sam', 'saq', 'sas', 'sat', 'saz', 'sba'
, 'sbp', 'sc', 'scn', 'sco', 'sd', 'sdc', 'sdh', 'se', 'see', 'seh', 'sei'
, 'sel', 'ses', 'sg', 'sga', 'sgs', 'sh', 'shi', 'shn', 'shu', 'si', 'sid'
, 'sk', 'sl', 'sli', 'sly', 'sm', 'sma', 'smj', 'smn', 'sms', 'sn', 'snk'
, 'so', 'sog', 'sq', 'sr', 'srn', 'srr', 'ss', 'ssy', 'st', 'stq', 'su', 'suk'
, 'sus', 'sux', 'sv', 'sw', 'swb', 'syc', 'syr', 'szl', 'ta', 'tcy', 'te'
, 'tem', 'teo', 'ter', 'tet', 'tg', 'th', 'ti', 'tig', 'tiv', 'tk', 'tkl'
, 'tkr', 'tl', 'tlh', 'tli', 'tly', 'tmh', 'tn', 'to', 'tog', 'tpi', 'tr'
, 'tru', 'trv', 'ts', 'tsd', 'tsi', 'tt', 'ttt', 'tum', 'tvl', 'tw', 'twq'
, 'ty', 'tyv', 'tzm', 'udm', 'ug', 'uga', 'uk', 'umb', 'und', 'ur', 'uz'
, 'vai', 've', 'vec', 'vep', 'vi', 'vls', 'vmf', 'vo', 'vot', 'vro', 'vun'
, 'wa', 'wae', 'wal', 'war', 'was', 'wbp', 'wo', 'wuu', 'xal', 'xh', 'xmf'
, 'xog', 'yao', 'yap', 'yav', 'ybb', 'yi', 'yo', 'yrl', 'yue', 'za', 'zap'
, 'zbl', 'zea', 'zen', 'zgh', 'zh', 'zu', 'zun', 'zxx', 'zza'
];

export type ScriptIdType = (
  'Adlm'| 'Afak'| 'Aghb'| 'Ahom'| 'Arab'| 'Armi'| 'Armn'| 'Avst'| 'Bali'
| 'Bamu'| 'Bass'| 'Batk'| 'Beng'| 'Bhks'| 'Blis'| 'Bopo'| 'Brah'| 'Brai'
| 'Bugi'| 'Buhd'| 'Cakm'| 'Cans'| 'Cari'| 'Cham'| 'Cher'| 'Cirt'| 'Copt'
| 'Cprt'| 'Cyrl'| 'Cyrs'| 'Deva'| 'Dogr'| 'Dsrt'| 'Dupl'| 'Egyd'| 'Egyh'
| 'Egyp'| 'Elba'| 'Elym'| 'Ethi'| 'Geok'| 'Geor'| 'Glag'| 'Gong'| 'Gonm'
| 'Goth'| 'Gran'| 'Grek'| 'Gujr'| 'Guru'| 'Hanb'| 'Hang'| 'Hani'| 'Hano'
| 'Hans'| 'Hant'| 'Hatr'| 'Hebr'| 'Hira'| 'Hluw'| 'Hmng'| 'Hmnp'| 'Hrkt'
| 'Hung'| 'Inds'| 'Ital'| 'Jamo'| 'Java'| 'Jpan'| 'Jurc'| 'Kali'| 'Kana'
| 'Khar'| 'Khmr'| 'Khoj'| 'Knda'| 'Kore'| 'Kpel'| 'Kthi'| 'Lana'| 'Laoo'
| 'Latf'| 'Latg'| 'Latn'| 'Lepc'| 'Limb'| 'Lina'| 'Linb'| 'Lisu'| 'Loma'
| 'Lyci'| 'Lydi'| 'Mahj'| 'Maka'| 'Mand'| 'Mani'| 'Marc'| 'Maya'| 'Medf'
| 'Mend'| 'Merc'| 'Mero'| 'Mlym'| 'Modi'| 'Mong'| 'Moon'| 'Mroo'| 'Mtei'
| 'Mult'| 'Mymr'| 'Nand'| 'Narb'| 'Nbat'| 'Newa'| 'Nkgb'| 'Nkoo'| 'Nshu'
| 'Ogam'| 'Olck'| 'Orkh'| 'Orya'| 'Osge'| 'Osma'| 'Palm'| 'Pauc'| 'Perm'
| 'Phag'| 'Phli'| 'Phlp'| 'Phlv'| 'Phnx'| 'Plrd'| 'Prti'| 'Qaag'| 'Rjng'
| 'Rohg'| 'Roro'| 'Runr'| 'Samr'| 'Sara'| 'Sarb'| 'Saur'| 'Sgnw'| 'Shaw'
| 'Shrd'| 'Sidd'| 'Sind'| 'Sinh'| 'Sogd'| 'Sogo'| 'Sora'| 'Soyo'| 'Sund'
| 'Sylo'| 'Syrc'| 'Syre'| 'Syrj'| 'Syrn'| 'Tagb'| 'Takr'| 'Tale'| 'Talu'
| 'Taml'| 'Tang'| 'Tavt'| 'Telu'| 'Teng'| 'Tfng'| 'Tglg'| 'Thaa'| 'Thai'
| 'Tibt'| 'Tirh'| 'Ugar'| 'Vaii'| 'Visp'| 'Wara'| 'Wcho'| 'Wole'| 'Xpeo'
| 'Xsux'| 'Yiii'| 'Zanb'| 'Zinh'| 'Zmth'| 'Zsye'| 'Zsym'| 'Zxxx'| 'Zyyy'
| 'Zzzz');

export const ScriptIdValues: ScriptIdType[] = [
  'Adlm', 'Afak', 'Aghb', 'Ahom', 'Arab', 'Armi', 'Armn', 'Avst', 'Bali'
, 'Bamu', 'Bass', 'Batk', 'Beng', 'Bhks', 'Blis', 'Bopo', 'Brah', 'Brai'
, 'Bugi', 'Buhd', 'Cakm', 'Cans', 'Cari', 'Cham', 'Cher', 'Cirt', 'Copt'
, 'Cprt', 'Cyrl', 'Cyrs', 'Deva', 'Dogr', 'Dsrt', 'Dupl', 'Egyd', 'Egyh'
, 'Egyp', 'Elba', 'Elym', 'Ethi', 'Geok', 'Geor', 'Glag', 'Gong', 'Gonm'
, 'Goth', 'Gran', 'Grek', 'Gujr', 'Guru', 'Hanb', 'Hang', 'Hani', 'Hano'
, 'Hans', 'Hant', 'Hatr', 'Hebr', 'Hira', 'Hluw', 'Hmng', 'Hmnp', 'Hrkt'
, 'Hung', 'Inds', 'Ital', 'Jamo', 'Java', 'Jpan', 'Jurc', 'Kali', 'Kana'
, 'Khar', 'Khmr', 'Khoj', 'Knda', 'Kore', 'Kpel', 'Kthi', 'Lana', 'Laoo'
, 'Latf', 'Latg', 'Latn', 'Lepc', 'Limb', 'Lina', 'Linb', 'Lisu', 'Loma'
, 'Lyci', 'Lydi', 'Mahj', 'Maka', 'Mand', 'Mani', 'Marc', 'Maya', 'Medf'
, 'Mend', 'Merc', 'Mero', 'Mlym', 'Modi', 'Mong', 'Moon', 'Mroo', 'Mtei'
, 'Mult', 'Mymr', 'Nand', 'Narb', 'Nbat', 'Newa', 'Nkgb', 'Nkoo', 'Nshu'
, 'Ogam', 'Olck', 'Orkh', 'Orya', 'Osge', 'Osma', 'Palm', 'Pauc', 'Perm'
, 'Phag', 'Phli', 'Phlp', 'Phlv', 'Phnx', 'Plrd', 'Prti', 'Qaag', 'Rjng'
, 'Rohg', 'Roro', 'Runr', 'Samr', 'Sara', 'Sarb', 'Saur', 'Sgnw', 'Shaw'
, 'Shrd', 'Sidd', 'Sind', 'Sinh', 'Sogd', 'Sogo', 'Sora', 'Soyo', 'Sund'
, 'Sylo', 'Syrc', 'Syre', 'Syrj', 'Syrn', 'Tagb', 'Takr', 'Tale', 'Talu'
, 'Taml', 'Tang', 'Tavt', 'Telu', 'Teng', 'Tfng', 'Tglg', 'Thaa', 'Thai'
, 'Tibt', 'Tirh', 'Ugar', 'Vaii', 'Visp', 'Wara', 'Wcho', 'Wole', 'Xpeo'
, 'Xsux', 'Yiii', 'Zanb', 'Zinh', 'Zmth', 'Zsye', 'Zsym', 'Zxxx', 'Zyyy'
, 'Zzzz'
];

export const enum ScriptId {
  Adlm = 'Adlm',
  Afak = 'Afak',
  Aghb = 'Aghb',
  Ahom = 'Ahom',
  Arab = 'Arab',
  Armi = 'Armi',
  Armn = 'Armn',
  Avst = 'Avst',
  Bali = 'Bali',
  Bamu = 'Bamu',
  Bass = 'Bass',
  Batk = 'Batk',
  Beng = 'Beng',
  Bhks = 'Bhks',
  Blis = 'Blis',
  Bopo = 'Bopo',
  Brah = 'Brah',
  Brai = 'Brai',
  Bugi = 'Bugi',
  Buhd = 'Buhd',
  Cakm = 'Cakm',
  Cans = 'Cans',
  Cari = 'Cari',
  Cham = 'Cham',
  Cher = 'Cher',
  Cirt = 'Cirt',
  Copt = 'Copt',
  Cprt = 'Cprt',
  Cyrl = 'Cyrl',
  Cyrs = 'Cyrs',
  Deva = 'Deva',
  Dogr = 'Dogr',
  Dsrt = 'Dsrt',
  Dupl = 'Dupl',
  Egyd = 'Egyd',
  Egyh = 'Egyh',
  Egyp = 'Egyp',
  Elba = 'Elba',
  Elym = 'Elym',
  Ethi = 'Ethi',
  Geok = 'Geok',
  Geor = 'Geor',
  Glag = 'Glag',
  Gong = 'Gong',
  Gonm = 'Gonm',
  Goth = 'Goth',
  Gran = 'Gran',
  Grek = 'Grek',
  Gujr = 'Gujr',
  Guru = 'Guru',
  Hanb = 'Hanb',
  Hang = 'Hang',
  Hani = 'Hani',
  Hano = 'Hano',
  Hans = 'Hans',
  Hant = 'Hant',
  Hatr = 'Hatr',
  Hebr = 'Hebr',
  Hira = 'Hira',
  Hluw = 'Hluw',
  Hmng = 'Hmng',
  Hmnp = 'Hmnp',
  Hrkt = 'Hrkt',
  Hung = 'Hung',
  Inds = 'Inds',
  Ital = 'Ital',
  Jamo = 'Jamo',
  Java = 'Java',
  Jpan = 'Jpan',
  Jurc = 'Jurc',
  Kali = 'Kali',
  Kana = 'Kana',
  Khar = 'Khar',
  Khmr = 'Khmr',
  Khoj = 'Khoj',
  Knda = 'Knda',
  Kore = 'Kore',
  Kpel = 'Kpel',
  Kthi = 'Kthi',
  Lana = 'Lana',
  Laoo = 'Laoo',
  Latf = 'Latf',
  Latg = 'Latg',
  Latn = 'Latn',
  Lepc = 'Lepc',
  Limb = 'Limb',
  Lina = 'Lina',
  Linb = 'Linb',
  Lisu = 'Lisu',
  Loma = 'Loma',
  Lyci = 'Lyci',
  Lydi = 'Lydi',
  Mahj = 'Mahj',
  Maka = 'Maka',
  Mand = 'Mand',
  Mani = 'Mani',
  Marc = 'Marc',
  Maya = 'Maya',
  Medf = 'Medf',
  Mend = 'Mend',
  Merc = 'Merc',
  Mero = 'Mero',
  Mlym = 'Mlym',
  Modi = 'Modi',
  Mong = 'Mong',
  Moon = 'Moon',
  Mroo = 'Mroo',
  Mtei = 'Mtei',
  Mult = 'Mult',
  Mymr = 'Mymr',
  Nand = 'Nand',
  Narb = 'Narb',
  Nbat = 'Nbat',
  Newa = 'Newa',
  Nkgb = 'Nkgb',
  Nkoo = 'Nkoo',
  Nshu = 'Nshu',
  Ogam = 'Ogam',
  Olck = 'Olck',
  Orkh = 'Orkh',
  Orya = 'Orya',
  Osge = 'Osge',
  Osma = 'Osma',
  Palm = 'Palm',
  Pauc = 'Pauc',
  Perm = 'Perm',
  Phag = 'Phag',
  Phli = 'Phli',
  Phlp = 'Phlp',
  Phlv = 'Phlv',
  Phnx = 'Phnx',
  Plrd = 'Plrd',
  Prti = 'Prti',
  Qaag = 'Qaag',
  Rjng = 'Rjng',
  Rohg = 'Rohg',
  Roro = 'Roro',
  Runr = 'Runr',
  Samr = 'Samr',
  Sara = 'Sara',
  Sarb = 'Sarb',
  Saur = 'Saur',
  Sgnw = 'Sgnw',
  Shaw = 'Shaw',
  Shrd = 'Shrd',
  Sidd = 'Sidd',
  Sind = 'Sind',
  Sinh = 'Sinh',
  Sogd = 'Sogd',
  Sogo = 'Sogo',
  Sora = 'Sora',
  Soyo = 'Soyo',
  Sund = 'Sund',
  Sylo = 'Sylo',
  Syrc = 'Syrc',
  Syre = 'Syre',
  Syrj = 'Syrj',
  Syrn = 'Syrn',
  Tagb = 'Tagb',
  Takr = 'Takr',
  Tale = 'Tale',
  Talu = 'Talu',
  Taml = 'Taml',
  Tang = 'Tang',
  Tavt = 'Tavt',
  Telu = 'Telu',
  Teng = 'Teng',
  Tfng = 'Tfng',
  Tglg = 'Tglg',
  Thaa = 'Thaa',
  Thai = 'Thai',
  Tibt = 'Tibt',
  Tirh = 'Tirh',
  Ugar = 'Ugar',
  Vaii = 'Vaii',
  Visp = 'Visp',
  Wara = 'Wara',
  Wcho = 'Wcho',
  Wole = 'Wole',
  Xpeo = 'Xpeo',
  Xsux = 'Xsux',
  Yiii = 'Yiii',
  Zanb = 'Zanb',
  Zinh = 'Zinh',
  Zmth = 'Zmth',
  Zsye = 'Zsye',
  Zsym = 'Zsym',
  Zxxx = 'Zxxx',
  Zyyy = 'Zyyy',
  Zzzz = 'Zzzz'
}

export type RegionIdType = (
  '001'| '002'| '003'| '005'| '009'| '011'| '013'| '014'| '015'| '017'| '018'
| '019'| '021'| '029'| '030'| '034'| '035'| '039'| '053'| '054'| '057'| '061'
| '142'| '143'| '145'| '150'| '151'| '154'| '155'| '202'| '419'| 'AC'| 'AD'
| 'AE'| 'AF'| 'AG'| 'AI'| 'AL'| 'AM'| 'AO'| 'AQ'| 'AR'| 'AS'| 'AT'| 'AU'| 'AW'
| 'AX'| 'AZ'| 'BA'| 'BB'| 'BD'| 'BE'| 'BF'| 'BG'| 'BH'| 'BI'| 'BJ'| 'BL'| 'BM'
| 'BN'| 'BO'| 'BQ'| 'BR'| 'BS'| 'BT'| 'BV'| 'BW'| 'BY'| 'BZ'| 'CA'| 'CC'| 'CD'
| 'CF'| 'CG'| 'CH'| 'CI'| 'CK'| 'CL'| 'CM'| 'CN'| 'CO'| 'CP'| 'CR'| 'CU'| 'CV'
| 'CW'| 'CX'| 'CY'| 'CZ'| 'DE'| 'DG'| 'DJ'| 'DK'| 'DM'| 'DO'| 'DZ'| 'EA'| 'EC'
| 'EE'| 'EG'| 'EH'| 'ER'| 'ES'| 'ET'| 'EU'| 'EZ'| 'FI'| 'FJ'| 'FK'| 'FM'| 'FO'
| 'FR'| 'GA'| 'GB'| 'GD'| 'GE'| 'GF'| 'GG'| 'GH'| 'GI'| 'GL'| 'GM'| 'GN'| 'GP'
| 'GQ'| 'GR'| 'GS'| 'GT'| 'GU'| 'GW'| 'GY'| 'HK'| 'HM'| 'HN'| 'HR'| 'HT'| 'HU'
| 'IC'| 'ID'| 'IE'| 'IL'| 'IM'| 'IN'| 'IO'| 'IQ'| 'IR'| 'IS'| 'IT'| 'JE'| 'JM'
| 'JO'| 'JP'| 'KE'| 'KG'| 'KH'| 'KI'| 'KM'| 'KN'| 'KP'| 'KR'| 'KW'| 'KY'| 'KZ'
| 'LA'| 'LB'| 'LC'| 'LI'| 'LK'| 'LR'| 'LS'| 'LT'| 'LU'| 'LV'| 'LY'| 'MA'| 'MC'
| 'MD'| 'ME'| 'MF'| 'MG'| 'MH'| 'MK'| 'ML'| 'MM'| 'MN'| 'MO'| 'MP'| 'MQ'| 'MR'
| 'MS'| 'MT'| 'MU'| 'MV'| 'MW'| 'MX'| 'MY'| 'MZ'| 'NA'| 'NC'| 'NE'| 'NF'| 'NG'
| 'NI'| 'NL'| 'NO'| 'NP'| 'NR'| 'NU'| 'NZ'| 'OM'| 'PA'| 'PE'| 'PF'| 'PG'| 'PH'
| 'PK'| 'PL'| 'PM'| 'PN'| 'PR'| 'PS'| 'PT'| 'PW'| 'PY'| 'QA'| 'QO'| 'RE'| 'RO'
| 'RS'| 'RU'| 'RW'| 'SA'| 'SB'| 'SC'| 'SD'| 'SE'| 'SG'| 'SH'| 'SI'| 'SJ'| 'SK'
| 'SL'| 'SM'| 'SN'| 'SO'| 'SR'| 'SS'| 'ST'| 'SV'| 'SX'| 'SY'| 'SZ'| 'TA'| 'TC'
| 'TD'| 'TF'| 'TG'| 'TH'| 'TJ'| 'TK'| 'TL'| 'TM'| 'TN'| 'TO'| 'TR'| 'TT'| 'TV'
| 'TW'| 'TZ'| 'UA'| 'UG'| 'UM'| 'UN'| 'US'| 'UY'| 'UZ'| 'VA'| 'VC'| 'VE'| 'VG'
| 'VI'| 'VN'| 'VU'| 'WF'| 'WS'| 'XA'| 'XB'| 'XK'| 'YE'| 'YT'| 'ZA'| 'ZM'| 'ZW'
| 'ZZ');
export const RegionIdValues: RegionIdType[] = [
  '001', '002', '003', '005', '009', '011', '013', '014', '015', '017', '018'
, '019', '021', '029', '030', '034', '035', '039', '053', '054', '057', '061'
, '142', '143', '145', '150', '151', '154', '155', '202', '419', 'AC', 'AD'
, 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW'
, 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM'
, 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD'
, 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CP', 'CR', 'CU', 'CV'
, 'CW', 'CX', 'CY', 'CZ', 'DE', 'DG', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EA', 'EC'
, 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'EU', 'EZ', 'FI', 'FJ', 'FK', 'FM', 'FO'
, 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP'
, 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU'
, 'IC', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM'
, 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ'
, 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC'
, 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR'
, 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG'
, 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH'
, 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'QO', 'RE', 'RO'
, 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK'
, 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TA', 'TC'
, 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV'
, 'TW', 'TZ', 'UA', 'UG', 'UM', 'UN', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG'
, 'VI', 'VN', 'VU', 'WF', 'WS', 'XA', 'XB', 'XK', 'YE', 'YT', 'ZA', 'ZM', 'ZW'
, 'ZZ'
];

export const enum RegionId {
  _001 = '001',
  _002 = '002',
  _003 = '003',
  _005 = '005',
  _009 = '009',
  _011 = '011',
  _013 = '013',
  _014 = '014',
  _015 = '015',
  _017 = '017',
  _018 = '018',
  _019 = '019',
  _021 = '021',
  _029 = '029',
  _030 = '030',
  _034 = '034',
  _035 = '035',
  _039 = '039',
  _053 = '053',
  _054 = '054',
  _057 = '057',
  _061 = '061',
  _142 = '142',
  _143 = '143',
  _145 = '145',
  _150 = '150',
  _151 = '151',
  _154 = '154',
  _155 = '155',
  _202 = '202',
  _419 = '419',
  AC = 'AC',
  AD = 'AD',
  AE = 'AE',
  AF = 'AF',
  AG = 'AG',
  AI = 'AI',
  AL = 'AL',
  AM = 'AM',
  AO = 'AO',
  AQ = 'AQ',
  AR = 'AR',
  AS = 'AS',
  AT = 'AT',
  AU = 'AU',
  AW = 'AW',
  AX = 'AX',
  AZ = 'AZ',
  BA = 'BA',
  BB = 'BB',
  BD = 'BD',
  BE = 'BE',
  BF = 'BF',
  BG = 'BG',
  BH = 'BH',
  BI = 'BI',
  BJ = 'BJ',
  BL = 'BL',
  BM = 'BM',
  BN = 'BN',
  BO = 'BO',
  BQ = 'BQ',
  BR = 'BR',
  BS = 'BS',
  BT = 'BT',
  BV = 'BV',
  BW = 'BW',
  BY = 'BY',
  BZ = 'BZ',
  CA = 'CA',
  CC = 'CC',
  CD = 'CD',
  CF = 'CF',
  CG = 'CG',
  CH = 'CH',
  CI = 'CI',
  CK = 'CK',
  CL = 'CL',
  CM = 'CM',
  CN = 'CN',
  CO = 'CO',
  CP = 'CP',
  CR = 'CR',
  CU = 'CU',
  CV = 'CV',
  CW = 'CW',
  CX = 'CX',
  CY = 'CY',
  CZ = 'CZ',
  DE = 'DE',
  DG = 'DG',
  DJ = 'DJ',
  DK = 'DK',
  DM = 'DM',
  DO = 'DO',
  DZ = 'DZ',
  EA = 'EA',
  EC = 'EC',
  EE = 'EE',
  EG = 'EG',
  EH = 'EH',
  ER = 'ER',
  ES = 'ES',
  ET = 'ET',
  EU = 'EU',
  EZ = 'EZ',
  FI = 'FI',
  FJ = 'FJ',
  FK = 'FK',
  FM = 'FM',
  FO = 'FO',
  FR = 'FR',
  GA = 'GA',
  GB = 'GB',
  GD = 'GD',
  GE = 'GE',
  GF = 'GF',
  GG = 'GG',
  GH = 'GH',
  GI = 'GI',
  GL = 'GL',
  GM = 'GM',
  GN = 'GN',
  GP = 'GP',
  GQ = 'GQ',
  GR = 'GR',
  GS = 'GS',
  GT = 'GT',
  GU = 'GU',
  GW = 'GW',
  GY = 'GY',
  HK = 'HK',
  HM = 'HM',
  HN = 'HN',
  HR = 'HR',
  HT = 'HT',
  HU = 'HU',
  IC = 'IC',
  ID = 'ID',
  IE = 'IE',
  IL = 'IL',
  IM = 'IM',
  IN = 'IN',
  IO = 'IO',
  IQ = 'IQ',
  IR = 'IR',
  IS = 'IS',
  IT = 'IT',
  JE = 'JE',
  JM = 'JM',
  JO = 'JO',
  JP = 'JP',
  KE = 'KE',
  KG = 'KG',
  KH = 'KH',
  KI = 'KI',
  KM = 'KM',
  KN = 'KN',
  KP = 'KP',
  KR = 'KR',
  KW = 'KW',
  KY = 'KY',
  KZ = 'KZ',
  LA = 'LA',
  LB = 'LB',
  LC = 'LC',
  LI = 'LI',
  LK = 'LK',
  LR = 'LR',
  LS = 'LS',
  LT = 'LT',
  LU = 'LU',
  LV = 'LV',
  LY = 'LY',
  MA = 'MA',
  MC = 'MC',
  MD = 'MD',
  ME = 'ME',
  MF = 'MF',
  MG = 'MG',
  MH = 'MH',
  MK = 'MK',
  ML = 'ML',
  MM = 'MM',
  MN = 'MN',
  MO = 'MO',
  MP = 'MP',
  MQ = 'MQ',
  MR = 'MR',
  MS = 'MS',
  MT = 'MT',
  MU = 'MU',
  MV = 'MV',
  MW = 'MW',
  MX = 'MX',
  MY = 'MY',
  MZ = 'MZ',
  NA = 'NA',
  NC = 'NC',
  NE = 'NE',
  NF = 'NF',
  NG = 'NG',
  NI = 'NI',
  NL = 'NL',
  NO = 'NO',
  NP = 'NP',
  NR = 'NR',
  NU = 'NU',
  NZ = 'NZ',
  OM = 'OM',
  PA = 'PA',
  PE = 'PE',
  PF = 'PF',
  PG = 'PG',
  PH = 'PH',
  PK = 'PK',
  PL = 'PL',
  PM = 'PM',
  PN = 'PN',
  PR = 'PR',
  PS = 'PS',
  PT = 'PT',
  PW = 'PW',
  PY = 'PY',
  QA = 'QA',
  QO = 'QO',
  RE = 'RE',
  RO = 'RO',
  RS = 'RS',
  RU = 'RU',
  RW = 'RW',
  SA = 'SA',
  SB = 'SB',
  SC = 'SC',
  SD = 'SD',
  SE = 'SE',
  SG = 'SG',
  SH = 'SH',
  SI = 'SI',
  SJ = 'SJ',
  SK = 'SK',
  SL = 'SL',
  SM = 'SM',
  SN = 'SN',
  SO = 'SO',
  SR = 'SR',
  SS = 'SS',
  ST = 'ST',
  SV = 'SV',
  SX = 'SX',
  SY = 'SY',
  SZ = 'SZ',
  TA = 'TA',
  TC = 'TC',
  TD = 'TD',
  TF = 'TF',
  TG = 'TG',
  TH = 'TH',
  TJ = 'TJ',
  TK = 'TK',
  TL = 'TL',
  TM = 'TM',
  TN = 'TN',
  TO = 'TO',
  TR = 'TR',
  TT = 'TT',
  TV = 'TV',
  TW = 'TW',
  TZ = 'TZ',
  UA = 'UA',
  UG = 'UG',
  UM = 'UM',
  UN = 'UN',
  US = 'US',
  UY = 'UY',
  UZ = 'UZ',
  VA = 'VA',
  VC = 'VC',
  VE = 'VE',
  VG = 'VG',
  VI = 'VI',
  VN = 'VN',
  VU = 'VU',
  WF = 'WF',
  WS = 'WS',
  XA = 'XA',
  XB = 'XB',
  XK = 'XK',
  YE = 'YE',
  YT = 'YT',
  ZA = 'ZA',
  ZM = 'ZM',
  ZW = 'ZW',
  ZZ = 'ZZ'
}
