//
// WARNING: this file was auto-generated by @phensley/cldr-compiler. DO NOT EDIT.
//

// eslint-disable-next-line max-len
export const weekFirstDay: { [x: string]: number } = {'001':2,AD:2,AE:7,AF:7,AG:1,AI:2,AL:2,AM:2,AN:2,AR:2,AS:1,AT:2,AU:2,AX:2,AZ:2,BA:2,BD:1,BE:2,BG:2,BH:7,BM:2,BN:2,BR:1,BS:1,BT:1,BW:1,BY:2,BZ:1,CA:1,CH:2,CL:2,CM:2,CN:2,CO:1,CR:2,CY:2,CZ:2,DE:2,DJ:7,DK:2,DM:1,DO:1,DZ:7,EC:2,EE:2,EG:7,ES:2,ET:1,FI:2,FJ:2,FO:2,FR:2,GB:2,GE:2,GF:2,GP:2,GR:2,GT:1,GU:1,HK:1,HN:1,HR:2,HU:2,ID:1,IE:2,IL:1,IN:1,IQ:7,IR:7,IS:2,IT:2,JM:1,JO:7,JP:1,KE:1,KG:2,KH:1,KR:1,KW:7,KZ:2,LA:1,LB:2,LI:2,LK:2,LT:2,LU:2,LV:2,LY:7,MC:2,MD:2,ME:2,MH:1,MK:2,MM:1,MN:2,MO:1,MQ:2,MT:1,MV:6,MX:1,MY:2,MZ:1,NI:1,NL:2,NO:2,NP:1,NZ:2,OM:7,PA:1,PE:1,PH:1,PK:1,PL:2,PR:1,PT:1,PY:1,QA:7,RE:2,RO:2,RS:2,RU:2,SA:1,SD:7,SE:2,SG:1,SI:2,SK:2,SM:2,SV:1,SY:7,TH:1,TJ:2,TM:2,TR:2,TT:1,TW:1,UA:2,UM:1,US:1,UY:2,UZ:2,VA:2,VE:1,VI:1,VN:2,WS:1,XK:2,YE:1,ZA:1,ZW:1};

// eslint-disable-next-line max-len
export const weekMinDays: { [x: string]: number } = {'001':1,AD:4,AN:4,AT:4,AX:4,BE:4,BG:4,CH:4,CZ:4,DE:4,DK:4,EE:4,ES:4,FI:4,FJ:4,FO:4,FR:4,GB:4,GF:4,GG:4,GI:4,GP:4,GR:4,GU:1,HU:4,IE:4,IM:4,IS:4,IT:4,JE:4,LI:4,LT:4,LU:4,MC:4,MQ:4,NL:4,NO:4,PL:4,PT:4,RE:4,RU:4,SE:4,SJ:4,SK:4,SM:4,UM:1,US:1,VA:4,VI:1};
