//
// WARNING: this file was auto-generated by @phensley/cldr-compiler. DO NOT EDIT.
//

/* tslint:disable-next-line */
export const weekFirstDay: { [x: string]: number } = {'001':1,AD:1,AE:6,AF:6,AG:7,AI:1,AL:1,AM:1,AN:1,AR:7,AS:7,AT:1,AU:7,AX:1,AZ:1,BA:1,BD:5,BE:1,BG:1,BH:6,BM:1,BN:1,BR:7,BS:7,BT:7,BW:7,BY:1,BZ:7,CA:7,CH:1,CL:1,CM:1,CN:7,CO:7,CR:1,CY:1,CZ:1,DE:1,DJ:6,DK:1,DM:7,DO:7,DZ:6,EC:1,EE:1,EG:6,ES:1,ET:7,FI:1,FJ:1,FO:1,FR:1,GB:1,GE:1,GF:1,GP:1,GR:1,GT:7,GU:7,HK:7,HN:7,HR:1,HU:1,ID:7,IE:7,IL:7,IN:7,IQ:6,IR:6,IS:1,IT:1,JM:7,JO:6,JP:7,KE:7,KG:1,KH:7,KR:7,KW:6,KZ:1,LA:7,LB:1,LI:1,LK:1,LT:1,LU:1,LV:1,LY:6,MA:6,MC:1,MD:1,ME:1,MH:7,MK:1,MM:7,MN:1,MO:7,MQ:1,MT:7,MV:5,MX:7,MY:1,MZ:7,NI:7,NL:1,NO:1,NP:7,NZ:1,OM:6,PA:7,PE:7,PH:7,PK:7,PL:1,PR:7,PT:1,PY:7,QA:6,RE:1,RO:1,RS:1,RU:1,SA:7,SD:6,SE:1,SG:7,SI:1,SK:1,SM:1,SV:7,SY:6,TH:7,TJ:1,TM:1,TN:7,TR:1,TT:7,TW:7,UA:1,UM:7,US:7,UY:1,UZ:1,VA:1,VE:7,VI:7,VN:1,WS:7,XK:1,YE:7,ZA:7,ZW:7};

/* tslint:disable-next-line */
export const weekMinDays: { [x: string]: number } = {'001':1,AD:4,AN:4,AT:4,AX:4,BE:4,BG:4,CH:4,CZ:4,DE:4,DK:4,EE:4,ES:4,FI:4,FJ:4,FO:4,FR:4,GB:4,GF:4,GG:4,GI:4,GP:4,GR:4,GU:1,HU:4,IE:4,IM:4,IS:4,IT:4,JE:4,LI:4,LT:4,LU:4,MC:4,MQ:4,NL:4,NO:4,PL:4,PT:4,RE:4,RU:4,SE:4,SJ:4,SK:4,SM:4,UM:1,US:1,VA:4,VI:1};
