//
// WARNING: this file was auto-generated by @phensley/cldr-compiler. DO NOT EDIT.
//

/* tslint:disable-next-line */
export const calendarIds: string[] = ['gregorian', 'islamic-umalqura', 'islamic', 'islamic-civil', 'islamic-tbla', 'persian', 'chinese', 'coptic', 'ethiopic', 'hebrew', 'indian', 'japanese', 'dangi', 'islamic-rgsa', 'buddhist', 'roc'];

/* tslint:disable-next-line */
export const calendarPrefData: { [x: string]: number[] } = {'001':[0],AE:[0,1,2,3,4],AF:[5,0,2,3,4],BH:[0,1,2,3,4],CN:[0,6],CX:[0,6],DJ:[0,2,3,4],DZ:[0,2,3,4],EG:[0,7,2,3,4],EH:[0,2,3,4],ER:[0,2,3,4],ET:[0,8],HK:[0,6],IL:[0,9,2,3,4],IN:[0,10],IQ:[0,2,3,4],IR:[5,0,2,3,4],JO:[0,2,3,4],JP:[0,11],KM:[0,2,3,4],KR:[0,12],KW:[0,1,2,3,4],LB:[0,2,3,4],LY:[0,2,3,4],MA:[0,2,3,4],MO:[0,6],MR:[0,2,3,4],OM:[0,2,3,4],PS:[0,2,3,4],QA:[0,1,2,3,4],SA:[1,0,2,13],SD:[0,2,3,4],SG:[0,6],SY:[0,2,3,4],TD:[0,2,3,4],TH:[14,0],TN:[0,2,3,4],TW:[0,15,6],YE:[0,2,3,4]};
