//
// WARNING: this file was auto-generated by @phensley/cldr-compiler. DO NOT EDIT.
//

export type ContextTransformType = (
  'calendar-field'| 'currencyName'| 'day-format-except-narrow'
| 'day-standalone-except-narrow'| 'era-abbr'| 'era-name'| 'keyValue'
| 'languages'| 'month-format-except-narrow'| 'month-standalone-except-narrow'
| 'number-spellout'| 'relative'| 'script'| 'typographicNames');

export const ContextTransformValues: ContextTransformType[] = [
  'calendar-field', 'currencyName', 'day-format-except-narrow'
, 'day-standalone-except-narrow', 'era-abbr', 'era-name', 'keyValue'
, 'languages', 'month-format-except-narrow', 'month-standalone-except-narrow'
, 'number-spellout', 'relative', 'script', 'typographicNames'
];

export const enum ContextTransform {
  CALENDAR_FIELD = 'calendar-field',
  CURRENCYNAME = 'currencyName',
  DAY_FORMAT_EXCEPT_NARROW = 'day-format-except-narrow',
  DAY_STANDALONE_EXCEPT_NARROW = 'day-standalone-except-narrow',
  ERA_ABBR = 'era-abbr',
  ERA_NAME = 'era-name',
  KEYVALUE = 'keyValue',
  LANGUAGES = 'languages',
  MONTH_FORMAT_EXCEPT_NARROW = 'month-format-except-narrow',
  MONTH_STANDALONE_EXCEPT_NARROW = 'month-standalone-except-narrow',
  NUMBER_SPELLOUT = 'number-spellout',
  RELATIVE = 'relative',
  SCRIPT = 'script',
  TYPOGRAPHICNAMES = 'typographicNames'
}
